# Generated by Django 2.1.7 on 2019-04-03 13:43

from django.db import migrations, models
import django.db.models.deletion
import random_forest.models_dataset


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255, unique=True)),
                ('deskripsi', models.TextField()),
                ('default_dataset', models.BooleanField(default=False)),
                ('file_dataset', models.FileField(upload_to='dataset/csv/', validators=[random_forest.models_dataset.validate_file_extension])),
                ('separator', models.CharField(choices=[('koma', 'Koma'), ('titik_koma', 'Titik Koma'), ('tab', 'Tab'), ('enter', 'Enter')], default='koma', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HyperparameterRF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_rf', models.BooleanField(default=False)),
                ('n_tree', models.CharField(default=10, max_length=255)),
                ('max_fitur', models.CharField(default='sqrt', max_length=255)),
                ('max_kedalaman', models.CharField(default=10, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SetFitur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fitur', models.TextField(blank=True, null=True)),
                ('default_fitur', models.BooleanField(default=False)),
                ('use_rf', models.BooleanField(default=False)),
                ('all_fitur', models.BooleanField(choices=[(True, 'Ya'), (False, 'Tidak')], default=True, max_length=255)),
                ('reduksi_null_fitur', models.BooleanField(choices=[(True, 'Ya'), (False, 'Tidak')], default=True, max_length=255)),
                ('reduksi_nilai_kurang_dari', models.CharField(max_length=255)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='random_forest.Dataset')),
            ],
        ),
        migrations.CreateModel(
            name='SetLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validate_label', models.BooleanField(default=False)),
                ('use_rf', models.BooleanField(default=False)),
                ('kolom_label', models.CharField(max_length=250)),
                ('nilai_label_kanker', models.CharField(max_length=255)),
                ('dataset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='random_forest.Dataset')),
            ],
        ),
    ]
