# Generated by Django 2.1.7 on 2019-04-04 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('random_forest', '0002_dataset_set_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='hyperparameterrf',
            name='default_hyperparameter',
            field=models.BooleanField(default=False),
        ),
    ]
