# Generated by Django 2.1.7 on 2019-04-04 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('random_forest', '0003_hyperparameterrf_default_hyperparameter'),
    ]

    operations = [
        migrations.CreateModel(
            name='RandomForest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('k_cv', models.CharField(default=5, max_length=255)),
                ('mean_accuracy', models.CharField(blank=True, max_length=255, null=True)),
                ('mean_sensitivity', models.CharField(blank=True, max_length=255, null=True)),
                ('mean_specifity', models.CharField(blank=True, max_length=255, null=True)),
                ('mean_time', models.CharField(blank=True, max_length=255, null=True)),
                ('tanggal_running', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='random_forest.Dataset')),
                ('hyperparameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='random_forest.HyperparameterRF')),
            ],
        ),
    ]
