# Generated by Django 2.1.7 on 2019-04-04 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('random_forest', '0004_randomforest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultRF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accuracy', models.CharField(blank=True, max_length=255, null=True)),
                ('sensitivity', models.CharField(blank=True, max_length=255, null=True)),
                ('specifity', models.CharField(blank=True, max_length=255, null=True)),
                ('time', models.CharField(blank=True, max_length=255, null=True)),
                ('randomforest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='random_forest.RandomForest')),
            ],
        ),
    ]
