# Generated by Django 2.1.7 on 2019-04-04 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('random_forest', '0005_resultrf'),
    ]

    operations = [
        migrations.AddField(
            model_name='randomforest',
            name='setfitur',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='random_forest.SetFitur'),
        ),
        migrations.AddField(
            model_name='randomforest',
            name='setlabel',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='random_forest.SetLabel'),
        ),
    ]
