# Generated by Django 2.1.7 on 2019-04-04 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('random_forest', '0006_auto_20190404_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randomforest',
            name='setfitur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='random_forest.SetFitur'),
        ),
        migrations.AlterField(
            model_name='randomforest',
            name='setlabel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='random_forest.SetLabel'),
        ),
    ]
