# Generated by Django 2.1.7 on 2019-04-04 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('random_forest', '0007_auto_20190404_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='randomforest',
            name='mean_accuracy',
        ),
        migrations.RemoveField(
            model_name='randomforest',
            name='mean_sensitivity',
        ),
        migrations.RemoveField(
            model_name='randomforest',
            name='mean_specifity',
        ),
        migrations.RemoveField(
            model_name='randomforest',
            name='mean_time',
        ),
        migrations.AddField(
            model_name='randomforest',
            name='rf_fitur_importance',
            field=models.FileField(default='coba.csv', upload_to='randomForest/fiturImportance/'),
        ),
        migrations.AddField(
            model_name='randomforest',
            name='rf_model',
            field=models.FileField(default='coba.csv', upload_to='randomForest/model/'),
        ),
        migrations.AddField(
            model_name='randomforest',
            name='rf_result',
            field=models.FileField(default='coba.csv', upload_to='randomForest/result/'),
        ),
    ]
