# Generated by Django 2.1.7 on 2019-04-05 08:06

from django.db import migrations, models
import random_forest.models_hyperparameterRF


class Migration(migrations.Migration):

    dependencies = [
        ('random_forest', '0008_auto_20190405_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hyperparameterrf',
            name='max_fitur',
            field=models.CharField(default='sqrt', max_length=255, validators=[random_forest.models_hyperparameterRF.validate_max_fitur]),
        ),
        migrations.AlterField(
            model_name='randomforest',
            name='rf_model',
            field=models.FileField(default='coba.pkl', upload_to='randomForest/model/'),
        ),
    ]
