# Generated by Django 2.1.7 on 2019-04-05 18:44

from django.db import migrations, models
import random_forest.models_randomForest


class Migration(migrations.Migration):

    dependencies = [
        ('random_forest', '0009_auto_20190405_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randomforest',
            name='k_cv',
            field=models.CharField(default=5, max_length=255, validators=[random_forest.models_randomForest.validate_k_cv]),
        ),
    ]
