# Generated by Django 2.1.7 on 2019-04-07 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('random_forest', '0010_auto_20190406_0144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultrf',
            name='randomforest',
        ),
        migrations.DeleteModel(
            name='ResultRF',
        ),
    ]
