# Generated by Django 2.1.7 on 2019-04-07 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('random_forest', '0011_auto_20190408_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setfitur',
            name='reduksi_nilai_kurang_dari',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
