# Generated by Django 2.1.7 on 2019-04-29 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('random_forest', '0012_auto_20190408_0200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setfitur',
            name='reduksi_nilai_kurang_dari',
        ),
        migrations.RemoveField(
            model_name='setfitur',
            name='reduksi_null_fitur',
        ),
        migrations.AddField(
            model_name='setfitur',
            name='subs_median_group_by_class',
            field=models.BooleanField(choices=[(True, 'Ya'), (False, 'Tidak')], default=True, max_length=255),
        ),
    ]
