# Generated by Django 2.1.7 on 2019-04-30 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('random_forest', '0014_hyperparameterrf_dataset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hyperparameterrf',
            name='dataset',
        ),
        migrations.AddField(
            model_name='setfitur',
            name='count_after_preparation',
            field=models.CharField(default=10, max_length=255),
        ),
    ]
