# Generated by Django 2.1.7 on 2019-05-08 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('random_forest', '0015_auto_20190430_2344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hyperparameterrf',
            name='max_kedalaman',
        ),
    ]
