# Generated by Django 2.1.7 on 2019-06-19 12:43

from django.db import migrations, models
import random_forest.models_hyperparameterRF


class Migration(migrations.Migration):

    dependencies = [
        ('random_forest', '0016_remove_hyperparameterrf_max_kedalaman'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='nama',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='separator',
            field=models.CharField(choices=[('koma', 'Koma'), ('titik_koma', 'Titik Koma'), ('tab', 'Tab'), ('enter', 'Enter')], default='koma', max_length=10),
        ),
        migrations.AlterField(
            model_name='hyperparameterrf',
            name='max_fitur',
            field=models.CharField(default='sqrt', max_length=10, validators=[random_forest.models_hyperparameterRF.validate_max_fitur]),
        ),
        migrations.AlterField(
            model_name='hyperparameterrf',
            name='n_tree',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='setfitur',
            name='count_after_preparation',
            field=models.CharField(default=10, max_length=10),
        ),
        migrations.AlterField(
            model_name='setlabel',
            name='kolom_label',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='setlabel',
            name='nilai_label_kanker',
            field=models.CharField(max_length=10),
        ),
    ]
