# Generated by Django 2.1.7 on 2019-06-19 12:43

from django.db import migrations, models
import random_forest.models_randomForest


class Migration(migrations.Migration):

    dependencies = [
        ('random_forest', '0017_auto_20190619_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randomforest',
            name='k_cv',
            field=models.IntegerField(default=5, validators=[random_forest.models_randomForest.validate_k_cv]),
        ),
    ]
