# Generated by Django 2.1.7 on 2019-06-19 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('random_forest', '0018_auto_20190619_1943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setfitur',
            old_name='subs_median_group_by_class',
            new_name='delete_fitur_with_null_val',
        ),
    ]
