# Generated by Django 2.2.3 on 2019-07-23 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('random_forest', '0019_auto_20190619_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='randomforest',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
