# Generated by Django 2.2.3 on 2019-07-24 08:59

from django.db import migrations, models
import random_forest.models_randomForest


class Migration(migrations.Migration):

    dependencies = [
        ('random_forest', '0020_auto_20190723_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randomforest',
            name='test_prosentase',
            field=models.IntegerField(default=5, validators=[random_forest.models_randomForest.validate_test_prosentase]),
        ),
    ]
