# Generated by Django 2.2.3 on 2019-07-24 09:47

from django.db import migrations, models
import random_forest.models_randomForest


class Migration(migrations.Migration):

    dependencies = [
        ('random_forest', '0021_auto_20190724_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randomforest',
            name='test_prosentase',
            field=models.IntegerField(default=30, validators=[random_forest.models_randomForest.validate_test_prosentase]),
        ),
    ]
