# Generated by Django 2.2.3 on 2019-07-27 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('random_forest', '0022_auto_20190724_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='randomforest',
            name='default_model',
            field=models.BooleanField(default=False),
        ),
    ]
