# Generated by Django 2.2.3 on 2019-07-30 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('random_forest', '0020_randomforest_selected'),
        ('random_forest', '0023_randomforest_default_model'),
    ]

    operations = [
    ]
