# Generated by Django 2.2.3 on 2019-07-30 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ULB', '0004_auto_20190724_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ulbdata',
            name='Time',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ulbdatalabelled',
            name='Time',
            field=models.FloatField(),
        ),
    ]
