# Generated by Django 2.2.3 on 2019-08-04 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ULB', '0005_auto_20190730_0347'),
    ]

    operations = [
        migrations.CreateModel(
            name='Models',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_supervised', models.BooleanField()),
            ],
        ),
    ]
